---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install Python 3
  ansible.builtin.package:
    name: "{{ python3_package_names }}"

- name: Install Python 3 development dependencies
  ansible.builtin.package:
    name: "{{ python3_development_package_names }}"
  when:
    - python_install_development_dependencies

- name: Install Python 2
  ansible.builtin.package:
    name: "{{ python2_package_names }}"
  when:
    - python_install_python2

- name: Install Python 2 development dependencies
  ansible.builtin.package:
    name: "{{ python2_development_package_names }}"
  when:
    - python_install_development_dependencies
    - python_install_python2
