---
# tasks file for python
- name: Determine Python package names (Amazon)
  set_fact:
    package_names:
      - python27
      - python36
  when: ansible_distribution == 'Amazon'

- name: Determine Python package names (Debian)
  set_fact:
    package_names:
      - python
      - python3
  when: ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux"

- name: Determine Python package names (Fedora)
  set_fact:
    package_names:
      - python2
      - python3
  when: ansible_distribution == 'Fedora'

- name: Install python
  package:
    name: "{{ package_names }}"
